"""Core package for AutoForexV2."""

from importlib.metadata import version

from core.accounts import Account, AccountId
from core.brokers import (
    Broker,
    BrokerOrderId,
    BrokerPositionId,
    OrderRequest,
    OrderRequestId,
    OrderResult,
    OrderResultMessageKey,
    OrderResultReason,
    OrderResultReasonCode,
    OrderSide,
    OrderStatus,
    OrderType,
    Position,
    PositionSide,
    message_key_for_order_result_reason,
)
from core.clock import local_timezone, now
from core.events import (
    ErrorCategory,
    ErrorCode,
    ErrorDetails,
    Event,
    EventError,
    EventMessageKey,
    EventSeverity,
    EventSource,
    EventType,
    EventTypeMetadata,
    StrategyAction,
    StrategyDecisionCode,
    StrategyDecisionReason,
    StrategyEvent,
    TradeSide,
    error_code_for_event_type,
    message_key_for_event_type,
    metadata_for_event_type,
)
from core.logging import CORE_LOGGER_NAME, LogLevel, configure_logging, get_logger
from core.models import (
    Currency,
    CurrencyPair,
    DomainModel,
    Metadata,
    Money,
    new_uuid,
)
from core.sources import (
    Candle,
    CandleGranularity,
    CSVCandleSchema,
    CSVDataSource,
    CSVDataSourceError,
    CSVTickSchema,
    CSVTimestampFormat,
    DataSource,
    SpreadFilter,
    SpreadFilteredDataSource,
    Tick,
    TickGranularity,
)
from core.strategies import (
    Strategy,
    StrategyContext,
    StrategyParameters,
    StrategyResult,
    StrategyState,
)
from core.tasks import (
    ALLOWED_TRANSITIONS,
    DEFAULT_TASK_STATE_MACHINE,
    BacktestTaskDefinition,
    BaseTaskDefinition,
    ExecutableTask,
    TaskAction,
    TaskDefinition,
    TaskFailure,
    TaskStateError,
    TaskStateMachine,
    TaskStatus,
    TaskTransition,
    TaskType,
    TradingTaskDefinition,
    normalize_task_action,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CORE_LOGGER_NAME",
    "DEFAULT_TASK_STATE_MACHINE",
    "Account",
    "AccountId",
    "BacktestTaskDefinition",
    "BaseTaskDefinition",
    "Broker",
    "BrokerOrderId",
    "BrokerPositionId",
    "CSVCandleSchema",
    "CSVDataSource",
    "CSVDataSourceError",
    "CSVTickSchema",
    "CSVTimestampFormat",
    "Candle",
    "CandleGranularity",
    "Currency",
    "CurrencyPair",
    "DataSource",
    "DomainModel",
    "ErrorCategory",
    "ErrorCode",
    "ErrorDetails",
    "Event",
    "EventError",
    "EventMessageKey",
    "EventSeverity",
    "EventSource",
    "EventType",
    "EventTypeMetadata",
    "ExecutableTask",
    "LogLevel",
    "Metadata",
    "Money",
    "OrderRequest",
    "OrderRequestId",
    "OrderResult",
    "OrderResultMessageKey",
    "OrderResultReason",
    "OrderResultReasonCode",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "Position",
    "PositionSide",
    "SpreadFilter",
    "SpreadFilteredDataSource",
    "Strategy",
    "StrategyAction",
    "StrategyContext",
    "StrategyDecisionCode",
    "StrategyDecisionReason",
    "StrategyEvent",
    "StrategyParameters",
    "StrategyResult",
    "StrategyState",
    "TaskAction",
    "TaskDefinition",
    "TaskFailure",
    "TaskStateError",
    "TaskStateMachine",
    "TaskStatus",
    "TaskTransition",
    "TaskType",
    "Tick",
    "TickGranularity",
    "TradeSide",
    "TradingTaskDefinition",
    "__version__",
    "configure_logging",
    "error_code_for_event_type",
    "get_logger",
    "local_timezone",
    "message_key_for_event_type",
    "message_key_for_order_result_reason",
    "metadata_for_event_type",
    "new_uuid",
    "normalize_task_action",
    "now",
]

__version__ = version("auto-forex-core")
